#filehandling
file = open("example.txt", "w")
file.close()
file = open("example.txt", "w")
file.write("Hello, this is my first file")
file.close()
file = open("example.txt", "r")
#file.write("Hello, this is my first file")
line1=file.readline()
print("line1:",line1)
file.close()
file=open("example.txt","a")
file.write("\nArpita")
file.write("\nECE")
file.close()